version: '3.8'

services:
  frontend:
    build:
      context: ./agenda-telefonica-front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./agenda-telefonica-front:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./agenda-telefonica-back
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./agenda-telefonica-back:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: